### ISSUE TITLE
Test vectors

### ISSUE THREAD

**Issue by martinthomson** [quicwg/quic-v2#17]
RFC 9001 had 'em and they were very helpful.

You might find [this script](https://gist.github.com/martinthomson/1f000d3e389b0bf1308e1043e141fbb9) to be useful.

**Comment by martinthomson** [comment]
Note that the TLS messages in that script hasn't been changed to include the version negotiation transport parameters.  If you want to publish it, then you'll need to work out how to do that, sorry.

**Comment by martinduke** [comment]
Finally done
