### ISSUE TITLE
HTTP/3 over QUICv2

### ISSUE THREAD

**Issue by DavidSchinazi** [quicwg/quic-v2#30]
At IETF 106, [we decided](https://github.com/quicwg/base-drafts/pull/3323) that HTTP/3 only runs over QUICv1. draft-ietf-quic-http still states `HTTP/3 relies on QUIC version 1 as the underlying transport`. Since that document is the reference in the ALPN registry for the ALPN string "h3", that means that `Alt-Svc: h3` is formally defined as "HTTP/3 over QUICv1". And that's exactly what all major browsers have implemented: if they see "h3" in Alt-Svc, they will send a QUICv1 initial.

Separately, the QUICv2 draft currently does not mention "h3" or HTTP/3 at all. If we were to publish QUICv2 as-is, that would mean that the only way that QUICv2 would ever be used with HTTP/3 would be for clients to send a QUICv1 initial and then have the server perform [compatible version negotiation](https://datatracker.ietf.org/doc/html/draft-ietf-quic-version-negotiation-05#section-4.3) from v1 to v2. That also means that QUICv2 endpoints will forever need to support QUICv1. That doesn't sound ideal.

This has been discussed before [on the list](https://mailarchive.ietf.org/arch/msg/quic/VuAWMvB8XFjpfK7kg6QaHn4KHqA/) and [at IETF 111](https://www.youtube.com/watch?v=R7q8cWIAIDQ&t=6262s) but we never reached consensus on a path forward.

Here are the options I see:

1. Leave everything as-is, and accept that QUICv2 requires QUICv1 and compatible version negotiation
2. Mint a new ALPN (e.g. "h3q2") that means "HTTP/3 over QUICv2" and can be used in Alt-Svc
3. Add a new parameter to Alt-Svc entries that specific the QUIC version (though servers would still need to support QUICv1 for old clients that don't know the parameter)

Given that we won't be minting that many QUIC versions, one new h3 ALPN per version seems simplest to me.

For what it's worth, I feel strongly that we should get WG consensus on the path forward here before we start the WGLC on QUICv2.

**Comment by LPardue** [comment]
Wearing no hats, option 2 is similar to how deployment have already approached supporting H3 over different QUIC v1 draft versions (albeit a bit implicitly. Something like "h3q2<-appended draft version>" would allow us to work on this until we are happy to mint a QUIC v2 RFC.

I would like to note though that a proliferation of tokens to be used in Alt-Svc does have practical implications for Multi-CDN scenarios https://github.com/httpwg/http-extensions/issues/1673. That might be a problem that we just need to let the HTTP WG figure out though. 

Of the three options here, 2) seems strongest to me.

**Comment by martinduke** [comment]
Beyond a potential explosion in ALPN registry entries, I see this as creating major obstacles to introducing and deprecating versions, if there are use cases besides h3.

After all, a sensible QUIC implementation will accept its ALPN code from the application running on top of it. If I want to roll out a new QUIC version in a protocol implementation, any application running over it also needs to modify its code to use that version. If I want to get rid of a bad version, I have to change all the applications to truly get rid of it.

Certainly, anything is scalable if we have a handful of ALPNs and versions. But this is an important tradeoff.

I'd prefer (3) -- Lucas, perhaps I don't understand the MultiCDN objection, but isn't a version-specific ALPN equally awkward for a MultiCDN rollout?

**Comment by DavidSchinazi** [comment]
This isn't about ALPN, it's really specific to Alt-Svc which is specific to HTTP. Use-cases beyond h3 don't need a new ALPN.

**Comment by martinduke** [comment]
> This isn't about ALPN, it's really specific to Alt-Svc which is specific to HTTP. Use-cases beyond h3 don't need a new ALPN.

Hmm, that substantially reduces my objection. I can live with that consensus, and if there is one we should get it in the applicability doc.

**Comment by LPardue** [comment]
Yeah sorry, David expressed it better than me. I should clarify that both options 2 and 3 have impact on Alt-Svc.

To add to my preference on option 2. Anything that uses ALPN for reporting or logging (such as the Web's resource timing nextHopProtocol) can benefit from information encoded in the ALPN ID itself. No extra work needed to encode transport-level details.

**Comment by martinduke** [comment]
To summarize some offline discussion:

Using an Alt-Svc parameter would limit impact on the ALPN registry. It would also mean that applications wouldn't need to change their advertised ALPN when their underlying QUIC implementations rolled out a new version. However, it opens up this edge case:

1. A v1-only client connects via TCP to an HTTP server that supports QUICv2 but not v1
2. The client is unmodified, so doesn't recognize the parameter
3. Seeing "h3" in alt-svc, it tries to connect via QUICv1, and the VN packet says it can't. Thus it has wasted an RTT where a v2-specific ALPN would have told it not to try in the first place and stay with TCP.

**Comment by LPardue** [comment]
Given this impact HTTP, it would be good to make the HTTP WG aware of the discussion and proposal

**Comment by martinduke** [comment]
Result of offline discussion with @martinthomson and @DavidSchinazi, who were the most vocal on the issue:

1) We will stick with "h3" ALPN. Some reasons:
(a) Compatible VN should totally negate any 1-RTT penalties, in practice, for v2.
(b) Longer term, adding/deprecating versions is much harder if you have to update all the applications.
(c) Some implementations will have great difficulty supporting different ALPNs for different versions.

2) I will try to get a draft started to add a quic-version parameter to Alt-Svc. Longer term, this will avoid most of the problems for h3 over future versions. 

3) I will add some text encouraging v2 servers to also support v1 and compatible VN.

4) We are punting the issue of incompatible versions for now. We may need to do a new ALPN, or perhaps the Alt-Svc parameter will be sufficient.
