### ISSUE TITLE
Consider adding an optional field in QUIC-v2 header?

### ISSUE THREAD

**Issue by Neo-ZK** [quicwg/quic-v2#40]
Yet QUIC have already used CID to indicate a connection, it can also add an option field to extend the QUIC ability. Imagine scenes below:
1. Set the real client IP in to QUIC packet: A common problem is that when QUIC server behind NAT, it's hard to get the real client IP address, if there is an option field, we can set the client IP address into QUIC packet, it's better than adding an Proxy-Protocol header for all QUIC packets.
2. Make custom-defined-routing by QUIC possible: Just like Segment Routing and Deterministic Routing, though which are currently an IP layer function, we can still implement it by QUIC.It is common to make some routing decisions at the upper level, eg, a CDN company can always get the network conditions between all pop node in its network topology, if QUIC has the ability of setting custom routing strategy, it's easily to realize a custom source routing strategy at the UDP level for the organization, just like this:
~~~
QUIC-pkt(Optional field: next-hop:2.2.2.2)----->pop Node1(1.1.1.1)------direct forward packet to 2.2.2.2----->dest
~~~
Some UDP-based SR is under deploying(see https://datatracker.ietf.org/doc/html/draft-zartbot-sr-udp-00), and it has also achieved good benefits, but I firmly believe that implementation at QUIC level will be a better solution.

**Comment by martinduke** [comment]
We have strong consensus in the working group not to add new features in v2.

A much more effective way to get this functionality is to write a draft that registers a new UDP option, see draft-tsvwg-udp-options. This would best be done in tsvwg, in my opinion.
