### ISSUE TITLE
ALPN

### ISSUE THREAD

**Issue by martinduke** [quicwg/quic-v2#5]
on slack some are saying we should roll a new h3 ALPN for running over quicv2. I cannot quite follow the argument but this is a better venue for the discussion.

**Comment by martinthomson** [comment]
You definitely need a new specification, because a different QUIC version might not be suitable.  You either say:

* h3 can be used with QUICv2, or
* h3q2 (or whatever new string you like) identifies HTTP/3 when running over QUICv2.

There are lots of arguments as to why you might choose to do one or the other.

**Comment by LPardue** [comment]
I'm swayed more toward a new ALP.N at the moment

**Comment by LPardue** [comment]
FWIW we painted ourselves into this corner. We punting on the problem and simply tied H3 to v1. Now we are actively trying to solve VN we might be able to pay back the tech debt. For example, a document that updates H3 to say that it can work over versions compatible with v1. Incompatible versions could still need to defined as a new application mapping,

**Comment by RyanTheOptimist** [comment]
Whatever we do, I think we need to ensure that servers can give sufficient information to clients via Alt-Svc so that the client can pick a compatible version (if any) and avoid VN. This could, then, be solved via Alt-Svc layer or via ALPN, but I think this is any important property.

**Comment by martinduke** [comment]
Well "avoiding VN" is only important to the extent that we can't do compatible VN.

**Comment by RyanTheOptimist** [comment]
I think we want to allow the existence of a server that only supports v2 and servers that only support v1.... and clients that only support v2 and clients that only support v1. Given this, there will be client : server pairs which do not support any mutually compatible options. It seems like it would be desirable for clients to be able to deduce this from Alt-Svc without needing to see the QUIC connection to the server fail?

**Comment by RyanTheOptimist** [comment]
Oh, and this text from the HTTP/3 docs is probably relevant:

>    HTTP/3 relies on QUIC version 1 as the underlying transport.  The use
>    of other QUIC transport versions with HTTP/3 MAY be defined by future
>    specifications.
