### ISSUE TITLE
Duplicate text

### ISSUE THREAD

**Issue by DavidSchinazi** [quicwg/quic-v2#65]
Draft currently states:
> If the server's version_information transport parameter does not contain a Chosen Version field equivalent to the version in the server's Handshake packet headers, the client MUST terminate the connection with a VERSION_NEGOTIATION_ERROR.

This repeats the QUIC VN document, should we remove it?

**Comment by martinduke** [comment]
Yes, good catch.

**Comment by martinduke** [comment]
fixed by #68
