### ISSUE TITLE
Editorial: I-D.ietf-dprive-dnsoquic is now RFC9250

### ISSUE THREAD

**Issue by rmarx** [quicwg/quic-v2#67]
DNS-over-QUIC was recently finalized as RFC9250 but the doc still refers to the -12 draft of the dprive document.

I'm not sure if this type of thing is usually (semi-)automatically caught during later stages of the review process, but I thought I'd mention it :)

**Comment by martinduke** [comment]
It probably does, but I fixed it. Thanks!

https://github.com/quicwg/quic-v2/commit/b960e2184b2dfc37fc3bc29d014800e6a54de6b3
