### ISSUE TITLE
Grease the packet type?

### ISSUE THREAD

**Issue by martinduke** [quicwg/quic-v2#7]
It would be a simple matter to switch around the packet type codes in long headers, e.g.

0x0 = Retry
0x1 = Handshake
0x2 = 0-RTT
0x3 = Initial

so no one ossifies on 0x0 = Initial.

**Comment by martinthomson** [comment]
I'm ambivalent on this.  It's fairly trivial to have the long header parsed in version-specific fashion, so it's easy to implement, but I'm not sure how much value it has.  It also makes reading packets slightly harder.
