### ISSUE TITLE
AD reveiw : Minor editorial comments

### ISSUE THREAD

**Issue by zaheduzzaman** [quicwg/quic-v2#72]
- here (https://github.com/quicwg/quic-v2/blob/3d2af981f8ed63b6256aadb2fec122a2df469fc6/draft-ietf-quic-v2.md?plain=1#L50) it is better that we call it QUIC version 1 not just QUIC. As later it is referred as QUIC version 1.

- here (https://github.com/quicwg/quic-v2/blob/3d2af981f8ed63b6256aadb2fec122a2df469fc6/draft-ietf-quic-v2.md?plain=1#L155) I would add reference to VN draft instead of calling it "that document"

- here (https://github.com/quicwg/quic-v2/blob/3d2af981f8ed63b6256aadb2fec122a2df469fc6/draft-ietf-quic-v2.md?plain=1#L169) i would add "packet" after "Initial" just to be clear, as we have now a initial version in VN draft.

**Comment by martinduke** [comment]
Thanks, fixed here
https://github.com/quicwg/quic-v2/pull/74
