### ISSUE TITLE
AD review : Interaction with 0-RTT packets

### ISSUE THREAD

**Issue by zaheduzzaman** [quicwg/quic-v2#73]
Section 7.3 in draft-ietf-quic-version-negotiation-09 required new versions to define interaction with 0-RTT packets. I am missing the interaction when 0-RTT packets are in client's first flight. This is a MUST requirement (of course the spec need to be approved, but we are doing VN and V2 work at the same time) that need to be followed.

**Comment by martinduke** [comment]
At the very end of [Section 4.1](https://quicwg.org/quic-v2/draft-ietf-quic-v2.html#name-compatible-negotiation-requ): 

> The client MUST NOT send 0-RTT packets using the negotiated version, even after processing a packet of that version from the server. Servers can apply original version 0-RTT packets to a connection without additional considerations.

Anything more you want to see there?

**Comment by zaheduzzaman** [comment]
Section 4.1 prohibits the client to send 0-RTT packets using negotiated version,  but does not say anything about how to handle the case when client sends 0-RTT packets in the first flight (with original version). as far as I can see , the VN draft requires new version documents to deal with this case - 
`If a future document
   wishes to define compatibility between two versions that support
   0-RTT, that document MUST address the scenario where there are 0-RTT
   packets in the client's first flight. `

let me know if I am misinterpreting something here. and if I am then this requires to be more clear in the text of this spec.

**Comment by martinthomson** [comment]
I think that the existing text is more or less fine, maybe with an edit.

> Servers can apply original version 0-RTT packets to a connection without additional considerations.

I might have instead said:

> Servers can accept 0-RTT and then process 0-RTT packets from the original version.

The "additional considerations" phrasing doesn't make a lot of sense to me.  I know what it means, but only because I know what it should mean.

**Comment by zaheduzzaman** [comment]
@martinthomson 's proposal makes it clearer, yes. that will do!!

**Comment by martinduke** [comment]
SGTM, fixed via https://github.com/quicwg/quic-v2/commit/3e690dc047a64deaafbde80cc636989096617c33
