### ISSUE TITLE
How does the client learn the negotiated version?

### ISSUE THREAD

**Issue by DavidSchinazi** [quicwg/quic-v2#78]
Let's assume the current scenario: the client sends `Long header = 1, ChosenVersion=1 ; AvailableVersions=(1,2)` and the server decides to do compatible VN v1-to-v2. Then the server send its ServerHello in an INITIAL at v1 (the draft explicitly allows this by making it a SHOULD and not a MUST: `The server SHOULD start sending its Initial packets using the negotiated version as soon as it decides to change.`).

At this point, there have only been QUICv1 packets exchanged. So the client can install handshake send keys for either version, but it is supposed to meet this requirement: `Both endpoints MUST send Handshake or 1-RTT packets using the negotiated version.` even though the client doesn't yet know what the negotiated version is.

We have text in the right direction: `Once the client has processed a packet using the negotiated version, it SHOULD send subsequent Initial packets using that version.` but that's not quite enough, we need to explain that the client learns about the version switch form the long headers and then validates it when it receives the server's ChosenVersion

**Comment by DavidSchinazi** [comment]
Since we've closed #76, let me reiterate a test case here that we need to make sure is handled by the resolution of this issue:
* Client sends an INITIAL(ClientHello) where LongHeaderVersion=v1, ChosenVersion=v1, and OtherVersions=v1,v2
* Client receives server INITIAL(ServerHello) where LongHeaderVersion=v1
* Client receives server HANDSHAKE(EncryptedExtensions) where LongHeaderVersion=v1, ChosenVersion=v2, and OtherVersions=v1,v2

**Comment by anrossi** [comment]
Shouldn't the server have the LongHeaderVersion=v2 on its HANDSHAKE packets, once it has upgraded the connection to the negotiated version?

**Comment by DavidSchinazi** [comment]
Yes the server isn't supposed to do that (sorry I should have made the clear). The question is: what should the client do when it sees the server misbehaving like this?

**Comment by anrossi** [comment]
If we're in agreement the server is misbehaving, then I would suggest the client close the connection.
