### ISSUE TITLE
Don't Change Labels

### ISSUE THREAD

**Issue by nibanks** [quicwg/quic-v2#9]
> The labels used in {{RFC9001}} to derive packet protection keys (Sec 5.1), header protection keys (Sec 5.4), Retry Integrity Tag keys (Sec 5.8), and key updates (Sec 6.1) change from "quic key" to "quicv2 key", from "quic iv" to "quicv2 iv", from "quic hp" to "quicv2 hp", and from "quic ku" to "quicv2 ku," to meet the guidance for new versions in Section 9.6 of that document.

Do we really need to change the labels? This will be a much bigger pain for me to integrate beyond the normal salt and retry secret changes that we regularly did for draft versions. What added benefit are the label changes giving?

**Comment by martinduke** [comment]
https://www.rfc-editor.org/rfc/rfc9001.html#key-diversity

it's a SHOULD

**Comment by nibanks** [comment]
Ok. It's probably worth some more discussion. Personally, I'd rather follow the model we set with draft versions. At least, that's what MsQuic is setup to easily handle.

**Comment by martinthomson** [comment]
This SHOULD is important; it will help keep your KDF from atrophy.  It was a little annoying to implement for me, but not overly so.

(Note that we have transcript diversity by virtue of including the version negotiation transport parameters, but I don't think that is sufficient.)

@nibanks, is this still a problem?

**Comment by nibanks** [comment]
It's an annoyance more than a problem. Our per-version abstraction will have to be modified to account for this, if we go forward with it, adding additional complexity.

**Comment by martinthomson** [comment]
Yeah, I can sympathize.  It was annoying to implement across an abstraction boundary for us also.  Luckily, we don't have to manage independent release cycles or anything truly awkward there.

**Comment by martinduke** [comment]
I don't think anyone is strenuously objecting to the current design; closing
